# This is a prototype profile declarative manifest in TOML format,
# supporting comments and the ability to invoke "shellHook" commands
# upon profile activation. See the flox(1) man page for more details.

# [environment]
#   LANG = "en_US.UTF-8"
#   LC_ALL = "$LANG"
#
# [aliases]
#   foo = "bar"
#   baz = "bing"
#
# [hooks]
#   sayhi = """
#     echo "Supercharged by flox!" 1>&2
#   """
#
# Edit below the "--- >8 ---" delimiter to define the list of packages to
# be installed, but note that comments and the ordering of packages will
# *not* be preserved with updates.
#
# Example package with optional constraints:
#   [packages."curl"]
#     channel = "nixpkgs-flox"
#     stability = "staging"
#     version = "7.79"

# ------------------------ >8 ------------------------

# ------------------------ >8 ------------------------
[packages]
  [packages."cowsay"]
  channel = "nixpkgs-flox"
  stability = "stable"

  [packages."fortune"]
  channel = "nixpkgs-flox"
  stability = "stable"

